[general]
openai_api_key = "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"  # Replace with your actual OpenAI API key
